### ISSUE TITLE
Use prespecified reference strain for variant calling and reporting

### ISSUE THREAD

**Issue by Accio** [bedapub/HBVouroboros#11]
Currently, the reference strain is inferred in a data-driven manner.

For regulatory agency reporting, we also want to specify a reference strain as the template against which the variant-calling is calling (instead of only inferred strain).

**Comment by Milad4849** [comment]
New committed branch score_vs_ref_strain now enables scoring against a ref strain. Due to the nature of snakemake, all relevant output files are still called have names including "inf", in reference to inferred. Might be better to change the output file names in the case of input reference strain. Only way i can think of doing this is to rename relevant files after the end of the run.
